default: &default  
  pool: 5
  timeout: 5000

  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  password: 123

development:  
  <<: *default
  database: prontopago_dev

test:  
  <<: *default
  database: prontopago_test

production:  
  <<: *default
  database: prontopago_prod
